# Generated by Django 3.1.7 on 2021-03-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_auto_20210313_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
